[package]
name = "easy-gltf"
version = "0.1.5"
authors = ["Florian Amsallem <florian.amsallem@epita.fr>"]
description = "glTF 2.0 loader with an easy to use output"
documentation = "https://docs.rs/easy-gltf"
repository = "https://github.com/flomonster/easy-gltf"
homepage = "https://github.com/flomonster/easy-gltf"
edition = "2018"
license = "MIT"
keywords = ["glTF", "3D", "asset", "model", "scene"]
exclude = [".github/"]

[dependencies]
cgmath = "0.18.0"
gltf = {version = "1.0.0", features = ["KHR_lights_punctual"]}
image = "0.24.1"
base64 = "0.13.0"
