[package]
name = "easy-gltf"
version = "0.1.0"
authors = ["Florian Amsallem <florian.amsallem@epita.fr>"]
description = "glTF 2.0 loader with an easy to use output"
documentation = "https://docs.rs/easy-gltf"
repository = "https://github.com/flomonster/easy-gltf"
homepage = "https://github.com/flomonster/easy-gltf"
edition = "2018"
license = "MIT"
keywords = ["glTF", "3D", "asset", "model", "scene"]

[dependencies]
cgmath="0.17.0"
gltf = {version = "0.15.2", features = ["KHR_lights_punctual"]}
image="0.23.6"
base64 = "0.13.0"
